cardano-community/koios-artifacts

- specs/templates/4-api-schemas.yaml
- topology/topology-testnet.json
Pool_info => active_stake will likely be null after an epoch transition (few seconds on guildnet, few minutes on testnet, and could be few hours on mainnet) while dbsync completes extracting-and-populating stake distribution
> Add clarification for active_stake

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
The version in OpenAPI schema wasn't used before, makes sense to keep it in sync with the gRest versioning before new changes are added
> Align version in specs to gRest repo

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
- tests/setup-tests.sh
Schema updates for the upcoming db-sync v13 release.
Added `400 - BadRequest` response code to schema.
Updated `schemathesis` test command. `--hypothesis-phases=explicit,generate` combined with `--hypothesis-max-examples=1` will first use the 32 explicit examples defined in schema (these are endpoints defined that HAVE the `parameters:` field). It will then generate one example for all 43 endpoints - for the no parameter endpoints these will be valid requests with responses validated, but for endpoints that do accept parameters, these will be invalid requests - hence the `BadRequest` code addition as code 400 was not defined before status code conformance is the only thing that can be validated here (with content validation already done on explicit examples run). 
Added nullable fields …
> Updates for db-sync v13

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Updates to match changes in pool_delegators endpoint. 
See:
issue #58
Endpoint changes: https://github.com/cardano-community/guild-operators/pull/1454
> [SPECS] update to pool_delegators

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
API specs had a few errors under output schema:
1. epoch_params: entropy => extra_entropy
2. epoch_params: cons_per_utxo_word => coins_per_utxo_size
3. block_list: Add proto_major, proto_minor to output
Additionally, reuse schema definitions where possible
> Fix schema inconsistencies reported by Dudi

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Schemathesis tests would fail for minting_txs that do not have any metadata attached.
Stake address can be null for non-account-related addresses.
> [SPEC] Make metadata fields nullable for minting txs

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Still not sure if we want to use `key` or `metalabel` for `/tx_metalabels` endpoint. Set to `key` at the moment.
Closes #78 #77
> [SPECS] Fix inconsistencies reported by Dudi

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Schema update due to change in tx_info endpoint to return a single output object, or null, for collateral_output
Unsure if ref is ok like this
> Update tx_info schema for collateral_output

- files/grest/rpc/assets/asset_info.sql
- files/grest/rpc/assets/asset_policy_info.sql
- files/grest/rpc/transactions/tx_info.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
1. [Minor output (data-type) change] - Convert tx_info: TTL values to string (as some values are far beyond billion) - assists cardano-community/koios-java-client#100
2. [Non-breaking] - Fix asset_info/asset_policy_info to show latest mint tx data (was an error in change before intended to do the same), and update asset_info->tx_hash to show latest (instead of oldest) tx
> Change TTL values in tx_info to string

- files/grest/cron/jobs/asset-info-cache-update.sh
- files/grest/rpc/01_cached_tables/asset_info_cache.sql
- files/grest/rpc/account/account_assets.sql
- files/grest/rpc/address/address_assets.sql
- files/grest/rpc/address/address_info.sql
- files/grest/rpc/assets/asset_info.sql
- files/grest/rpc/assets/asset_info_bulk.sql
- files/grest/rpc/assets/asset_policy_info.sql
- files/grest/rpc/assets/asset_policy_list.sql
- files/grest/rpc/transactions/tx_info.sql
- files/grest/rpc/transactions/tx_utxos.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/3-api-requestBodies.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
- specs/templates/example-map.json
- New asset_info_cache table
- Update rpc's where it makes sense to add decimals
- New asset_info_bulk rpc that takes bulk input. Current asset_info is untouched and is to be phased out.
Making sure the cache table is populated and the correctness of data. 
Performance testing to make sure both cache table and rpc's perform as expected. 
Supporting bulk asset requests reduces the number of queries needed and the cache table helps reduce the server load for each call while adding a scheduled load. 
#138 & #127
Tests have been done but as it adds a new cache table, updates rpc's, and has schema changes. All these things need to be verified to be correct. The asset info cache table is updated every 1 min, so new mints could take up to this limit at worst before some fields in the …
> New asset_info_cache table

- .github/workflows/main.yml
As discussed, any commits against any branch containing this workflow would replicate that branch history across to `koios-official` repo, which indirectly allows creation of alias that gradually holds any future branches that are modified
> Add workflow to sync repo

- projects.json
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/1-api-info.yaml
Few minor updates to list of projects:
- Remove list from API specs site and link them to koios.rest instead.
- Move CSCLI to CLI
- Add ADABox and MusicBox
- Add MeshJS and Mesh SDK (subsumes #152 - thanks @jinglescode )
- Add both Python libraries (for now - they would not want to merge due to style and completeness, but it could be an option in future for them to collaborate)
- Add logos (need to check with the rest or add links to uploaded versions for upcoming website, the current values are just to add template examples)
> Update projects list of community tools/libraries/projects using Koios

- files/grest/rpc/01_cached_tables/pool_info_cache.sql
- files/grest/rpc/account/account_addresses.sql
- files/grest/rpc/account/account_assets.sql
- files/grest/rpc/account/account_history.sql
- files/grest/rpc/account/account_rewards.sql
- files/grest/rpc/account/account_updates.sql
- files/grest/rpc/address/address_assets.sql
- files/grest/rpc/address/address_info.sql
- files/grest/rpc/assets/asset_history.sql
- files/grest/rpc/assets/asset_info.sql
- files/grest/rpc/assets/asset_info_bulk.sql
- files/grest/rpc/assets/policy_asset_info.sql
- files/grest/rpc/script/script_redeemers.sql
- files/grest/rpc/transactions/tx_utxos.sql
Switch all JSON references to JSONB (non-breaking for Koios endpoints consumption):
- Helps columns be kept consistent
- Allows use of filters in PostgREST URL as `cs.[{"key":"value"}]` , allowing filters for arrays.
- Faster to read (tho slower to form) - output performance should not have much impact for 1000 observations (sure, some JSON arrays might be larger, but still - the overhead in larger scheme for creating JSON vs JSONB shouldn't be as big)
> Switch JSON references to JSONB

- files/grest/rpc/01_cached_tables/asset_info_cache.sql
- files/grest/rpc/pool/pool_list.sql
- files/grest/rpc/pool/pool_updates.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/api-main.yaml
- Fix Asset Info Cache to not rely on being able to decode policy ID (bad data on IO repo)
- Handle Pool_list to check metadata entries that have not been populated in pool_offline_data (closes #109 from Koios point of view)
- Fix pool_updates to use pmr_id instead of pool_offline_data.id (wasnt reported earlier, but the endpoint was showing wrong data)
- Update account_info_cached description to clarify it is effective for registered accounts
> Apply Fixes from testing on non-mainnet networks

- files/grest/rpc/01_cached_tables/asset_info_cache.sql
- files/grest/rpc/account/account_assets.sql
- files/grest/rpc/address/address_assets.sql
- files/grest/rpc/address/address_info.sql
- files/grest/rpc/transactions/tx_info.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/2-api-params.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/example-map.json
- Bump up margin for tx rollback lookup for asset_info_cache to 1000 , as 100 is too small a margin for 2-3 blocks , which can contain more than 100 transactions (of which if oldest transaction contains a mint, it will not get into the cache)
- Specs:
- Fix examples in for preprod/preview
- Update tx_info > plutus_contracts > address to be nullable
- For `asset_list` object in address/account/tx related endpoints - reduce strictness with asset_info_cache, making it a `LEFT JOIN` instead of `INNER JOIN` in case the cache does not (yet) have an entry for those assets - since it's only used for decimals. The asset_info/policy_asset_info/asset_addresses/asset_nft_address/policy_asset_list endpoints have more dependency on this cache - they're untouched
- Asset info cache was tested based on …
> Minor patches for koios-1.0.10

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/4-api-schemas.yaml
`tx_utxos` was never updated to include assets/scripts/datum/references. While this should be fixed (likely as a new endpoint `utxo_info` while `tx_utxos` remains as an alias), the current PR is simply to address the current state of koios-1.0.10, to represent what query is.
We would follow up with new PR to add missing data to `utxo_info` and use this endpoint for backward compatibility, addresses 1st part of #186
> Fix specs for tx_utxos endpoint, to be able to re-tag koios-1.0.10

- files/grest/rpc/01_cached_tables/active_stake_cache.sql
Currently, active stake cache uses max(epoch_no) from existing tables to run delta cache on. But this may not always be accurate for pool and epoch, as during setup - values for epoch prior may not be available. Stake Snapshot Cache would provides data an epoch earlier to these tables, thus - relying on max(epoch_no) is no longer an accurate outcome.
Account's active stake  cache does not require maintaining historical information and can be left as-is.
Found recently that some of our instances reported empty array for pool_history endpoint. On verifying, found out epoch as well as pool cache tables could have missing entries due to our current mode of execution. This only started showing up recently on fresh instances restored via snapshot, wherein snapshot cache would fill entries prior …
> Update active stake cache to use control table

- files/grest/cron/jobs/active-stake-cache-update.sh
- files/grest/cron/jobs/asset-info-cache-update.sh
- files/grest/cron/jobs/epoch-info-cache-update.sh
- files/grest/cron/jobs/pool-history-cache-update.sh
- files/grest/cron/jobs/stake-distribution-new-accounts-update.sh
- files/grest/cron/jobs/stake-distribution-update.sh
- files/grest/cron/jobs/stake-snapshot-cache.sh
Update cron jobs (except asset registry cache) to exit if database has not received block in past 5 minutes
Starting cache update too early can risk slowing the sync process further (as well as the cache itself could be stale/redundant)
Applied on my instance while database was synching to avoid triggering another run, while after on tip ensured those cron jobs ran
> Update [most] cron jobs to exit if the database has not received block in 5 mins

- files/grest/rpc/address/address_txs.sql
- files/grest/rpc/address/credential_txs.sql
The input tx_id fields are not filtered by `_after_block_height` , this PR addresses the same
> addresses: Filter input tx IDs by _after_block_height

- files/grest/rpc/03_utilities/cip67.sql
- files/grest/rpc/03_utilities/cip68.sql
- files/grest/rpc/assets/asset_info_bulk.sql
- files/grest/rpc/assets/policy_asset_info.sql
ASCII output now strips CIP-68 label from the hex string before trying to convert the name to ASCII.
Needs additional tests to verify result correctness. 
Closes #253
> Add CIP-68 utility functions to be used by asset functions

- files/grest/rpc/assets/asset_txs.sql
- Include transaction where asset is burnt , as it is outside of input/output view
- Add a distinct on transaction hash
#274
> Include burn asset transactions in asset_txs

- files/grest/rpc/transactions/tx_info.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/4-api-schemas.yaml
closes https://github.com/cardano-community/koios-artifacts/issues/277
*Needs specs update
> tx_info: new logic for spend contracts mapping to inputs

- files/grest/rpc/01_cached_tables/pool_history_cache.sql
- files/grest/rpc/pool/pool_delegators.sql
- files/grest/rpc/pool/pool_history.sql
Added helper function for fetching history for a given epoch range for one to all pools, can be utilized for populating cache and is used in updated pool_history function that performs calculations on the fly for the most recent 3 epochs (to facilitate reward table update lag)
> Changes to facilitate on-the-fly calculation of pool_history data for most recent 3 epochs to deal with reward table population lag

- files/grest/rpc/01_cached_tables/asset_info_cache.sql
- files/grest/rpc/assets/asset_info.sql
- files/grest/rpc/assets/asset_info_bulk.sql
- files/grest/rpc/assets/policy_asset_info.sql
- files/grest/rpc/assets/policy_asset_mints.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/4-api-schemas.yaml
- asset_info_cache: Remove unused info from asset-info-cache
- asset_info_cache: Split out latest minting tx with metadata (vs overall latest)
- [policy_]asset_info: Use last_mint_meta_tx_id and fallback to last_mint_tx_id from asset info cache
> Asset Info Cache patch

- files/grest/rpc/01_cached_tables/pool_history_cache.sql
- files/grest/rpc/02_indexes/13_3_00.sql
dbsync 13.3.0.0 introduces pool_stat table, which contains number of blocks/delegators/stake and voting power historically. This means we no longer need to create aggregate of these from block or epoch_stake table ourselves.
> Make use of pool_stat instead of epoch_stake for pool_history_cache

- files/grest/rpc/02_indexes/13_3_00.sql
- files/grest/rpc/03_utilities/cip129.sql
- files/grest/rpc/account/account_info.sql
- files/grest/rpc/account/account_info_cached.sql
- files/grest/rpc/governance/committee_info.sql
- files/grest/rpc/governance/committee_votes.sql
- files/grest/rpc/governance/drep_delegators.sql
- files/grest/rpc/governance/drep_info.sql
- files/grest/rpc/governance/drep_list.sql
- files/grest/rpc/governance/drep_metadata.sql
- files/grest/rpc/governance/drep_updates.sql
- files/grest/rpc/governance/drep_votes.sql
- files/grest/rpc/governance/proposal_list.sql
- files/grest/rpc/governance/proposal_votes.sql
- files/grest/rpc/governance/proposal_voting_summary.sql
- files/grest/rpc/governance/voter_proposal_list.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/1-api-info.yaml
- specs/templates/2-api-params.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
- specs/templates/example-map.json
> Koios v1.2.0 Release

- files/grest/rpc/02_indexes/13_3_00.sql
- files/grest/rpc/02_indexes/13_5_0_2.sql
- files/grest/rpc/governance/proposal_voting_summary.sql
- files/grest/rpc/governance/voter_proposal_list.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/1-api-info.yaml
- specs/templates/4-api-schemas.yaml
Extra fields added to display number of abstain votes by dreps, SPOs and committee members.
> Additional abstain vote count fields added

- files/grest/rpc/governance/drep_info.sql
Marked as inactive 1 epoch before it should.
> fix for drep_info regarding active state

- files/grest/rpc/000_utilities/cip5.sql
Bech32 stake address generation using pg_cardano didn't set script flag correctly and instead creating all addresses as key addresses.
> Script fix for cip5_hex_to_stake_addr

- files/grest/rpc/00_blockchain/totals.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/4-api-schemas.yaml
Adds total `treasury_donation`, `treasury_withdrawal` and `reserve_withdrawal` to `/totals`.
Closes #347
> fea(rpc): Add treasure and reserve movements to /totals

- specs/createspecs.py
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/2-api-params.yaml
- specs/templates/3-api-requestBodies.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
Formats the API specs so that everything uses double quotes, removes trailing whitespaces etc.
Updates the `createspecs.py` to automatically detect the correct indentation so that individual spec placeholder files can be correctly indented, e.g. `2-api-params.yaml` can use the regular two space indentation now:
```
parameters:
_after_block_height:
...
```
```
parameters:
_after_block_height:
...
```
> chore(specs): format API specs

- files/grest/rpc/governance/proposal_list.sql
- files/grest/rpc/pool/pool_calidus_keys.sql
Fix multiple calidus with same nonce by using extra order by clause, so that earliest definition for a given nonce is utilized
Reported by Martin originally, was an issue by Chris (STR8) doing multiple calidus registrations with same nonce.
> Fix multiple calidus with same nonce

- files/grest/rpc/governance/proposal_list.sql
- files/grest/rpc/governance/voter_proposal_list.sql
- files/grest/rpc/transactions/tx_info.sql
- specs/templates/4-api-schemas.yaml
withdrawal information for gov action is now always an array instead of null or array; 
updated tx_info endpoint's _governance output building to use json array syntax to match earlier change to proposal_list endpoint
> Proposal list spec change to use array for withdrawal information

- files/grest/rpc/01_cached_tables/epoch_info_cache.sql
Epoch info cache rule for average block reward insert was wrong - should follow the same insert rule as total_rewards.
Closes #371
> fix: average block reward for epoch insert
