- .gitignore
- README.md
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
Update for repository map and TG group invite link.
> Update README and TG link

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Update API schema for: https://github.com/cardano-community/guild-operators/pull/1388
> [SPECS] Update metadata keys to strings

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/3-api-requestBodies.yaml
- specs/templates/api-main.yaml
Update for: https://github.com/cardano-community/guild-operators/pull/1389
> [SPECS] Update pool_metadata requestBody

- topology/topology-testnet.json
Adding my testnet Koios ( reqlez ).
> Add reqlez to testnet Koios

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
- specs/templates/4-api-schemas.yaml
- Fix block_height references for /tip and /blocks endpoint 
- Leftover metalabels number > string reference
> API spec fixes

- projects.json
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
- specs/templates/4-api-schemas.yaml
- Fix asset_names field
- add CardaStat to project list
- Rename CCVault to Eternl
- Move CLI to seperate section
> Spec and site Updates

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/2-api-params.yaml
- specs/templates/4-api-schemas.yaml
Schema update for https://github.com/cardano-community/guild-operators/pull/1402.
> Asset schema update

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Changes from [PR for grest `*_txs` updates](https://github.com/cardano-community/guild-operators/pull/1409)
> Corresponding changes for @cardano-community/guild-operators#1409

- projects.json
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
> Added CNFT.IO

- projects.json
add TosiDrop to Koios projects list
GitHub for the front-end is here: https://github.com/TosiDrop/vm-frontend
> add TosiDrop to Koios projects

- projects.json
> Adding Python Library and Raw Cardano Explorer projects.json

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
- specs/templates/4-api-schemas.yaml
API schema change for cardano-community/guild-operators#1417.
> [SPECS] Make date formats consistent

- projects.json
Added cscli to the list of community projects.
The `projects.json` file.
To highlight another useful tool for/from the community that uses Koios.
> Added cscli to list of projects

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
API schema change for cardano-community/guild-operators#1415.
> [SPECS] Add rewards data to epoch_info

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/api-main.yaml
Add missing parameter to API spec.
> [SPEC] Missing epoch_no parameter for /account_history

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Schema update for casting timestamps to integers: cardano-community/guild-operators#1460
> [SPEC] Cast timestamps to integers

- topology/topology-guild.json
- topology/topology-mainnet.json
- topology/topology-testnet.json
Updating DNS Name for Digital Syndicate Mainnet Node
Update Digital Syndicate DNS Name
> Topology - Update Nodes for Huth

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
API schema update to go along with cardano-community/guild-operators/pull/1468.
> [SPECS] Update asset_history/asset_info spec

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Update specs to match changes in tx_info
> [SPECS]: tx_info

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/api-main.yaml
Corresponding changes for [cardano-community/guild-operators/1474](https://github.com/cardano-community/guild-operators/pull/1474)
> Change tx_metalabels to RPC from view

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Closes #73 and #74
Depends on update in [RPC update for gRest epoch params](https://github.com/cardano-community/guild-operators/pull/1484)
> Update schema as per feedback received

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Closes #72 , corresponding gRest PR [here](https://github.com/cardano-community/guild-operators/pull/1500)
> Add inline_datum and reference_script to addr_info

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
Schema addition for: https://github.com/cardano-community/guild-operators/pull/1505
> [SPEC] Add /epoch_block_protocols to schema

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Add new `meta_json` field and fix some schema issues.
> [SPEC] Historical pool metadata + fixes

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
Schema change for cardano-community/guild-operators#1511
> [SPECS] Add sigma field to /pool_info

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/3-api-requestBodies.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
- specs/templates/example-map.json
Schema changes for cardano-community/guild-operators#1504.
> [SPEC] Bulk RPCs schema update

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
- specs/templates/2-api-params.yaml
- specs/templates/3-api-requestBodies.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
- specs/templates/example-map.json
> Bump Koios version to 1.0.7

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/1-api-info.yaml
Add TosiDrop the the webpage as community project
Just added a single line for  - [TosiDrop](https://tosidrop.io)
Increase the amount of projects using Koios
NA
NA
> Add TosiDrop

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
Schema changes fo:  https://github.com/cardano-community/guild-operators/pull/1542 and https://github.com/cardano-community/guild-operators/pull/1543
Also closes: https://github.com/cardano-community/koios-artifacts/issues/101
> [SPEC] Align metadata schema between tx_info and tx_metadata

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/2-api-params.yaml
- specs/templates/4-api-schemas.yaml
Minor text-updates/bug fixes for Koios 1.0.8 specs, that were reported since the release.
Since these are only fixing specs, there isnt a breaking change that will require updates from consumers or instance providers
> Fix bugs reported in specs for koios-1.0.8 (non breaking)

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/3-api-requestBodies.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
- specs/templates/example-map.json
Schema change for https://github.com/cardano-community/guild-operators/commit/13cca87b53209bf08c3a627a7d92a9be7f47d6d4
> Update spec for datum_info endpoint

- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-testnet.yaml
- specs/templates/4-api-schemas.yaml
To go along with https://github.com/cardano-community/guild-operators/pull/1559
> [SPEC] Update schema for asset object consistency

- topology/topology-preprod.json
> Added homer to preprod topology

- grafana-dashboards/guild.json
- grafana-dashboards/koios-servers.json
- topology/topology-guild.json
- topology/topology-mainnet.json
- topology/topology-preprod.json
- topology/topology-preview.json
- topology/topology-testnet.json
Updated Koios dashboard to cater for prometheus update reporting each instance, also synthesize variables
> Update dashboards to cater for 2 haproxy instances

- topology/topology-preview.json
> Added homer to preview topology

- projects.json
Adding Raw Cardano Explorer Logo
If he can access to the image
Improve website design
> Adding Raw Cardano Explorer Logo

- files/grest/cron/jobs/asset-registry-update.sh
> Update Asset Info Cache entry whenever asset registry cache has updates

- topology/topology-mainnet.json
> Update topology-mainnet.json - adding new homer-redoracle instance

- files/grest/rpc/01_cached_tables/pool_history_cache.sql
- files/grest/rpc/pool/pool_history.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
Add member_rewards to pool_history_cache and pool_history endpoint
Closes #203
Tested on guildnet local instance
> Add member_rewards to pool_history_cache and pool_history endpoint

- files/grest/cron/jobs/active-stake-cache-update.sh
- files/grest/cron/jobs/asset-info-cache-update.sh
- files/grest/cron/jobs/epoch-info-cache-update.sh
- files/grest/cron/jobs/pool-history-cache-update.sh
- files/grest/cron/jobs/stake-distribution-new-accounts-update.sh
- files/grest/cron/jobs/stake-distribution-update.sh
- files/grest/cron/jobs/stake-snapshot-cache.sh
> fix for tip check in cron jobs

- projects.json
Added my laravel package to the clients list
Lines 44 to 47
There has been no PHP library for the Koios APi yet
All endpoints have been tested by me by calling them from a controller.
> Laravel PHP client added

- files/grest/rpc/02_indexes/13_1_00.sql
- files/grest/rpc/assets/asset_info_bulk.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
TODO:
[x] - Add schema definition for the new field in response.
> Adds CIP67/68 asset metadata support to asset_info endpoint

- projects.json
> Update projects.json - Adding SPO Scripts to Community Tools

- topology/topology-preprod.json
- topology/topology-preview.json
Adding BBHMM for preprod instance and updated existing preview instance
check the files so they are formatted correctly and can access the port and ip
Add's BBHMM new Koios 1.1.1 instances in there
None, just added more resources
tested access to the ip and port
> Adding BBHMM for preprod instance and updated existing preview instance

- files/grest/cron/jobs/active-stake-cache-update.sh
- files/grest/rpc/01_cached_tables/active_stake_cache.sql
- files/grest/rpc/01_cached_tables/epoch_info_cache.sql
- files/grest/rpc/assets/asset_nft_address.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/1-api-info.yaml
- specs/templates/example-map.json
Finalise v1.1.1 release for tagging:
> Koios v1.1.1

- projects.json
Add RosenBridge to https://koios.rest/community.html#projects-building-on-koios
> Add RosenBridge to the koios home page

- projects.json
> update with gero

- projects.json
Update the new link for Tosidrop
Change from old site tosidrop.io to new site tosidrop.me
> Update new URL for tosidrop.me on projects.json

- topology/topology-preview.json
Updating my instance info on preview.
> chore: Update preview topology

- files/grest/rpc/pool/pool_owner_history.sql
Added extra conditions to restrict the pool_updates of interest as well as epoch_stake records range that's unique to a given pool_update
Closes #333
> Fix for https://github.com/cardano-community/koios-artifacts/issues/333

- files/grest/rpc/governance/committee_info.sql
Fix for issue reported by Martin on sanchonet that's in a state of no confidence while koios report latest committee back instead of null. 
Needs to be tested
> Fix for when committee is in no confidence mode

- topology/topology-mainnet.json
- topology/topology-preview.json
> chore: update topology

- specs/templates/4-api-schemas.yaml
Spec adjustment following a fix to proposal list to use array representation for withdrawals. couple of minor typos to existing descriptions.
> Spec adjustment following a fix to proposal list 

- files/grest/rpc/governance/drep_voting_power_history.sql
Added logic for upper bound on epoch shown in drep voting power histo…y to be the epoch of de-registration, if that was the last action for a given drep - to prevent useless zero values being returned for possibly hundreds of epochs for hundreds of dreps
As described above
As described above
> Upper bound limit on epoch no for drep voting power history

- files/grest/rpc/address/address_info.sql
- files/grest/rpc/script/reference_script_utxos.sql
- files/grest/rpc/transactions/tx_utxos.sql
- specs/results/koiosapi-guild.yaml
- specs/results/koiosapi-mainnet.yaml
- specs/results/koiosapi-preprod.yaml
- specs/results/koiosapi-preview.yaml
- specs/templates/4-api-schemas.yaml
- specs/templates/api-main.yaml
Addresses issue raised in #372
> Add reference_script_utxos

- files/grest/rpc/governance/committee_info.sql
- files/grest/rpc/transactions/tx_by_metalabel.sql
`committee_info` update for no confidence state with null for quorum and members, with proposal id and tx hash referring to the no confidence proposal.
#340
> committee_info update for no confidence
